host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: 'ubi:8'
    operating_system:
      name: ubi
      version: "8.0"
    python_version: "3.6"
    recommendation_type: latest
    limit_latest_versions: 5
