language: python
sudo: required
services:
- docker
python:
- '3.6'
script:
- pip3 install pipenv
- pipenv install --dev
- pipenv run coala
deploy:
- provider: script
  script: bash build.sh
  on:
    branch: master
env:
  matrix:
  - DOCKER_USER=fridex
  global:
  - secure: YphlOnEIbJRZowhmSUXtT1CHzqBEs5lBt2qJQjgtL+eBtZGDKpVJzXzVR8YbzH3z/boLVTZPTzUkDhKy/hkx11Cn+3r/1Ucs4RAWQiWCV4ttdeuAujclGr6jxw4ExQqPcvPvKJLD/7nc7iV7pT2OO3of3VOLw08Ja/bakMP/Ch3wq/VaLPjULjzDuRrX/9JzEtV6v3c4vfFjc9ibtYPDMs9A9biz2o7tQ0xEMfzzjYiEyFzn0S+vm+YtYTYdbEM5PkE9ZOLpBfxcD6/EXUjoBTUzZNobL4CMd2SI9N3rh9ETBmwOe9IHnkl5aMVr0WwbQHtoGu+2SzsTY7QoCzV0Gs0i/iHIeTOm/NsIRpInjn9h3GmcOflcgXHzD80Muzpr0AgDpEq1S6O5KzGsWgCRc/EG7fV0tOVX3jtWjQbllF67fMvc1tBd+qFZpX5Ib4id2e8+WuQWzfY7PG03Q2gYuhI+3HkF1Y5wDJ4iHtpYYeaQFkLuJnAZko6q45xgea+X8aYSgcR5hMWN6u8PaSdIcI++4Hi39VI7Gush8HFQvVfobCfBSWeUJxM7LVZ0XrFOlsJoNC5kMGCSYjICJn4R0ggCqHgLH5q3h4kMmw6lj45XUhUPXpwLNFd/3v4xE9PR2pjchKL6uGgDW8HXrFnxF0wT4Q/PbewrxFByP07IgDA=
  - secure: p0JPsDDzqVPbaOimy0hW5MpI9SWq5RFAkQGA5pJd53FlKYZ57UY2ZrxIcf2X+XvESdcnR7ymktsoXmxIegUjlpMmjfh+tEJQk06CrGfcsKAc3HDwHb8qhId8jMlrkVHtB8dDCL2qTzGxRtySESd3qsY2b8hruY+YZJ9VwqeKi8jGzlzkguq+JoUPzVJAYGDYQy/KnfGQZwudp/WcE6vhEG0pnMFLbo2tc7xSF4YR6gy8TQc5OIlBXkfOCENn4+INS0YesIej7oLVeDsYn6MrsuodG3GXvRMlKy5v3luXjd7DEx+nOOj7ViPZcmTJoRyVdRNfbFJELc2MalWTr7qmrXSgA/JwibLnfhUHNkCnlnkI6WcQqmgblvIRS+wjQE5dq27rHB4Seakf+2LHkbpLTThRxktq1GOZ9u5qiSbznOzwkqHtGyw6shWHAAh18NJiklz7tPYXyqq333Mgm4cWGGkMxlO7YmuGG4uawE41VqKDkSiEvIFV7qMMb0KiZny5rdWrctWjaDiy0BdffWQpYPga3LvnNKYhWIIW5EVZzW8uGAyvXUoYWUsbjrZp3zqqAhpzl2/FRFdiP3VTy5cRnLp6E0SgJWtlDINYvBA93IyvvIfPNnZL5jG8f3MRwOctq5SQIiAq+Dl5TlKk7u8C1DBJaV5p6rYHNGx/AUgTfHI=
